# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Hugrid - Grid Theme For Hugo"
theme = "Hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Waxanimations"
    subtitle = "Hit me up, for contacts and so on."
    author = "Pavel Kanyshev"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Purchase Poster"

    # Footer text
    footertext = "Made by [Magimug](magimug.net), [Hugo](http://gohugo.io) and [me](https://github.com/4mago)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
